
import React, { useState, useEffect, useRef } from 'react';
import { 
    RecipeSections,
    ArticleComponents,
    generateRelatedKeywords,
    generateFAQs,
    generateInternalLinks,
    generateExternalLinks,
    generateFullArticle,
    regenerateArticle,
    BillingRequiredError,
} from '../services/geminiService';
import { saveToHistory, updateHistoryItem } from '../services/historyService';
import { LoadingSpinner } from './LoadingSpinner';
import { ErrorMessage } from './ErrorMessage';
import { GeneratedArticleDisplay } from './GeneratedArticleDisplay';

type Page = 'home' | 'extractor' | 'analyzer' | 'compressor' | 'about' | 'privacy' | 'contact' | 'history' | 'history-viewer';

interface ArticleComponentsFormProps {
  keyword: string;
  analysisResult: string;
  recipeSections: RecipeSections;
  userRelatedKeywords: string;
  userInternalLinks: string;
  onNavigate: (page: Page) => void;
  targetRegion?: string;
  targetLanguage?: string;
}

interface LabeledTextareaProps {
    id: string;
    label: string;
    value: string;
    onChange: (value: string) => void;
    rows?: number;
    placeholder?: string;
    isLoading?: boolean;
}

const LabeledTextarea: React.FC<LabeledTextareaProps> = ({ id, label, value, onChange, rows = 5, placeholder, isLoading }) => (
    <div>
        <label htmlFor={id} className="block text-lg font-semibold text-sky-400 mb-2">{label}</label>
        <textarea
            id={id}
            value={value}
            onChange={(e) => onChange(e.target.value)}
            rows={rows}
            placeholder={placeholder}
            disabled={isLoading}
            className="w-full p-3 bg-slate-900/50 border border-slate-700 rounded-lg focus:ring-2 focus:ring-sky-500 focus:border-sky-500 transition-all duration-300 placeholder-slate-500 text-slate-200 disabled:opacity-70 font-sans leading-relaxed"
        />
    </div>
);

// Helper Icons
const SparklesIcon = () => (
    <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 3v4M3 5h4M6 17v4m-2-2h4m5-16l2.286 6.857L21 12l-5.714 3.214L13 21l-2.286-6.857L5 12l5.714-3.214L13 3z" />
    </svg>
);

const ArrowRightIcon = () => (
    <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 ml-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M14 5l7 7m0 0l-7 7m7-7H3" />
    </svg>
);

export const ArticleComponentsForm: React.FC<ArticleComponentsFormProps> = ({ 
    keyword, 
    analysisResult, 
    recipeSections, 
    userRelatedKeywords, 
    userInternalLinks, 
    onNavigate,
    targetRegion = 'United States',
    targetLanguage = 'English'
}) => {
    const [components, setComponents] = useState<ArticleComponents>({
        targetKeyword: keyword,
        relatedKeywords: userRelatedKeywords,
        internalLinks: userInternalLinks,
        externalLinks: '',
        ingredients: recipeSections.ingredients.join('\n'),
        instructions: recipeSections.instructions.join('\n'),
        nutrition: recipeSections.nutritionFacts,
        faqs: '',
        competitorAnalysis: analysisResult,
        category: recipeSections.category || '',
    });

    const [isLoading, setIsLoading] = useState(false);
    const [loadingMessage, setLoadingMessage] = useState('');
    const [error, setError] = useState<string | null>(null);
    const [isBillingError, setIsBillingError] = useState(false);
    
    // Output state
    const [generatedArticle, setGeneratedArticle] = useState<string | null>(null);
    const [savedArticleId, setSavedArticleId] = useState<string | undefined>(undefined);
    const [isRegenerating, setIsRegenerating] = useState(false);

    // Track auto-generation status
    const hasAutoGenerated = useRef(false);

    useEffect(() => {
        const isFrenchContext = targetRegion === 'France' && targetLanguage === 'French';
        const isUSContext = targetRegion === 'United States' && targetLanguage === 'English';

        if ((isFrenchContext || isUSContext) && !hasAutoGenerated.current) {
            hasAutoGenerated.current = true;
            
            const autoGenerate = async () => {
                setIsLoading(true);
                setLoadingMessage(`Auto-generating ${targetLanguage} content (FAQs & Links)...`);
                try {
                    const [faqs, links] = await Promise.all([
                        generateFAQs(analysisResult, targetLanguage),
                        generateExternalLinks(keyword, analysisResult, targetRegion, targetLanguage)
                    ]);
                    
                    setComponents(prev => ({
                        ...prev,
                        faqs: faqs,
                        externalLinks: links
                    }));
                } catch (e) {
                    console.error("Auto-generation failed:", e);
                    // We don't block user if auto-gen fails, they can try buttons
                } finally {
                    setIsLoading(false);
                }
            };
            autoGenerate();
        }
    }, [targetRegion, targetLanguage, analysisResult, keyword]);

    const handleComponentChange = (key: keyof ArticleComponents, value: string) => {
        setComponents(prev => ({ ...prev, [key]: value }));
    };

    const handleGenerateFAQs = async () => {
        setIsLoading(true);
        setLoadingMessage('Generating FAQs...');
        setError(null);
        try {
            const faqs = await generateFAQs(analysisResult, targetLanguage);
            handleComponentChange('faqs', faqs);
        } catch (e: any) {
            handleError(e);
        } finally {
            setIsLoading(false);
        }
    };

    const handleGenerateInternalLinks = async () => {
        setIsLoading(true);
        setLoadingMessage('Generating internal link ideas...');
        setError(null);
        try {
            const links = await generateInternalLinks(keyword);
            handleComponentChange('internalLinks', links);
        } catch (e: any) {
             handleError(e);
        } finally {
            setIsLoading(false);
        }
    };

    const handleGenerateExternalLinks = async () => {
        setIsLoading(true);
        setLoadingMessage(`Finding authoritative ${targetLanguage} links...`);
        setError(null);
        try {
            const links = await generateExternalLinks(keyword, analysisResult, targetRegion, targetLanguage);
            handleComponentChange('externalLinks', links);
        } catch (e: any) {
             handleError(e);
        } finally {
            setIsLoading(false);
        }
    };

    const handleGenerateArticle = async () => {
        setIsLoading(true);
        setLoadingMessage('Writing your high-ranking article...');
        setError(null);
        try {
            const article = await generateFullArticle(components);
            setGeneratedArticle(article);
            
            // Save to history immediately
            const saved = saveToHistory({
                title: extractTitle(article),
                keyword: components.targetKeyword,
                content: article,
                components: components,
            });
            if (saved) {
                setSavedArticleId(saved.id);
            }
        } catch (e: any) {
             handleError(e);
        } finally {
            setIsLoading(false);
        }
    };

    const handleRegenerateArticle = async (feedback: string) => {
        if (!generatedArticle) return;
        setIsRegenerating(true);
        setError(null);
        try {
            const newArticle = await regenerateArticle(components, generatedArticle, feedback);
            setGeneratedArticle(newArticle);
            if (savedArticleId) {
                updateHistoryItem(savedArticleId, { content: newArticle });
            }
        } catch (e: any) {
             handleError(e);
        } finally {
            setIsRegenerating(false);
        }
    };

    const handleError = (e: any) => {
        console.error(e);
        if (e instanceof BillingRequiredError) {
            setError(`${e.message} You can find more information about billing and API keys at: `);
            setIsBillingError(true);
        } else {
            setError(e instanceof Error ? e.message : 'An unexpected error occurred.');
            setIsBillingError(false);
        }
    };

    const extractTitle = (content: string) => {
        const match = content.match(/\[ARTICLE_START\]\s*#\s*(.*)/);
        return match ? match[1].trim() : 'Untitled Article';
    };
    
    const handleSelectApiKey = async () => {
        if (typeof window.aistudio !== 'undefined' && typeof window.aistudio.openSelectKey === 'function') {
            await window.aistudio.openSelectKey();
            setError(null);
            setIsBillingError(false);
        } else {
            setError("API key selection tool not available.");
        }
    };

    if (generatedArticle) {
        return (
            <GeneratedArticleDisplay 
                articleData={generatedArticle}
                components={components}
                onBack={() => setGeneratedArticle(null)}
                onRegenerate={handleRegenerateArticle}
                isRegenerating={isRegenerating}
                onNavigate={onNavigate}
                savedArticleId={savedArticleId}
            />
        );
    }

    if (isLoading) {
        return <LoadingSpinner message={loadingMessage} />;
    }

    return (
        <section className="w-full bg-slate-800/60 backdrop-blur-sm rounded-xl shadow-2xl p-6 md:p-8 border border-slate-700 animate-fade-in">
             <div className="text-center mb-10">
                <h2 className="text-3xl font-bold text-transparent bg-clip-text bg-gradient-to-r from-sky-500 via-blue-500 to-indigo-600 mb-2">
                    Refine Article Components
                </h2>
                <p className="text-slate-400">Review and tweak the AI-generated building blocks before writing the final article.</p>
            </div>

            {error && (
                <div className="mb-6">
                    <ErrorMessage message={error} />
                    {isBillingError && (
                        <div className="text-center mt-4">
                            <a href="https://ai.google.dev/gemini-api/docs/billing" target="_blank" rel="noopener noreferrer" className="text-blue-400 hover:underline mb-4 block">ai.google.dev/gemini-api/docs/billing</a>
                            <button onClick={handleSelectApiKey} className="px-6 py-2 font-bold text-white bg-blue-600 rounded-lg shadow-lg hover:bg-blue-700">Select Billed API Key</button>
                        </div>
                    )}
                </div>
            )}

            <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
                {/* Left Column */}
                <div className="space-y-6">
                    <LabeledTextarea 
                        id="targetKeyword" 
                        label="Target Keyword" 
                        value={components.targetKeyword} 
                        onChange={(v) => handleComponentChange('targetKeyword', v)} 
                        rows={1}
                    />
                    <LabeledTextarea 
                        id="category" 
                        label="Recipe Category" 
                        value={components.category} 
                        onChange={(v) => handleComponentChange('category', v)} 
                        rows={1}
                    />
                     <LabeledTextarea 
                        id="relatedKeywords" 
                        label="Related Keywords" 
                        value={components.relatedKeywords} 
                        onChange={(v) => handleComponentChange('relatedKeywords', v)} 
                        rows={3}
                    />
                    <div className="space-y-2">
                         <div className="flex justify-between items-end">
                            <label htmlFor="internalLinks" className="block text-lg font-semibold text-sky-400">Internal Links</label>
                            <button onClick={handleGenerateInternalLinks} className="text-sm px-3 py-1 bg-slate-700 hover:bg-slate-600 rounded-md text-slate-300 transition-colors flex items-center">
                                <SparklesIcon /> Suggest Ideas
                            </button>
                        </div>
                        <textarea
                            id="internalLinks"
                            value={components.internalLinks}
                            onChange={(e) => handleComponentChange('internalLinks', e.target.value)}
                            rows={4}
                            placeholder="Anchor Text: URL (one per line)"
                            className="w-full p-3 bg-slate-900/50 border border-slate-700 rounded-lg focus:ring-2 focus:ring-sky-500 text-slate-200"
                        />
                    </div>
                     <div className="space-y-2">
                         <div className="flex justify-between items-end">
                            <label htmlFor="externalLinks" className="block text-lg font-semibold text-sky-400">External Links</label>
                            <button onClick={handleGenerateExternalLinks} className="text-sm px-3 py-1 bg-slate-700 hover:bg-slate-600 rounded-md text-slate-300 transition-colors flex items-center">
                                <SparklesIcon /> Find Sources
                            </button>
                        </div>
                         <textarea
                            id="externalLinks"
                            value={components.externalLinks}
                            onChange={(e) => handleComponentChange('externalLinks', e.target.value)}
                            rows={4}
                            placeholder={`Anchor Text: URL (${targetLanguage} sources)`}
                            className="w-full p-3 bg-slate-900/50 border border-slate-700 rounded-lg focus:ring-2 focus:ring-sky-500 text-slate-200"
                        />
                    </div>
                </div>

                {/* Right Column */}
                <div className="space-y-6">
                    <LabeledTextarea 
                        id="ingredients" 
                        label="Ingredients List" 
                        value={components.ingredients} 
                        onChange={(v) => handleComponentChange('ingredients', v)} 
                    />
                     <LabeledTextarea 
                        id="instructions" 
                        label="Instructions" 
                        value={components.instructions} 
                        onChange={(v) => handleComponentChange('instructions', v)} 
                    />
                    <LabeledTextarea 
                        id="nutrition" 
                        label="Nutrition Facts" 
                        value={components.nutrition} 
                        onChange={(v) => handleComponentChange('nutrition', v)} 
                        rows={3}
                    />
                     <div className="space-y-2">
                         <div className="flex justify-between items-end">
                            <label htmlFor="faqs" className="block text-lg font-semibold text-sky-400">FAQs</label>
                            <button onClick={handleGenerateFAQs} className="text-sm px-3 py-1 bg-slate-700 hover:bg-slate-600 rounded-md text-slate-300 transition-colors flex items-center">
                                <SparklesIcon /> Generate FAQs
                            </button>
                        </div>
                        <textarea
                            id="faqs"
                            value={components.faqs}
                            onChange={(e) => handleComponentChange('faqs', e.target.value)}
                            rows={4}
                            placeholder="Q: Question?&#10;A: Answer."
                            className="w-full p-3 bg-slate-900/50 border border-slate-700 rounded-lg focus:ring-2 focus:ring-sky-500 text-slate-200"
                        />
                    </div>
                </div>
            </div>

            <div className="mt-10 pt-6 border-t border-slate-700 flex justify-center">
                <button
                    onClick={handleGenerateArticle}
                    className="w-full sm:w-auto px-10 py-4 font-bold text-xl text-white bg-gradient-to-r from-sky-500 to-indigo-600 rounded-lg shadow-lg hover:from-sky-600 hover:to-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-slate-900 focus:ring-sky-500 transition-all duration-300 flex items-center justify-center transform hover:-translate-y-1"
                >
                    Generate Full Article <ArrowRightIcon />
                </button>
            </div>
        </section>
    );
}